<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universities = [
            // Federal Universities
            [
                'name' => 'University of Lagos',
                'short_name' => 'UNILAG',
                'slug' => 'unilag',
                'type' => 'federal',
                'location' => 'Akoka, Lagos',
                'state' => 'Lagos',
                'website' => 'https://unilag.edu.ng',
                'sort_order' => 1,
            ],
            [
                'name' => 'University of Ibadan',
                'short_name' => 'UI',
                'slug' => 'ui',
                'type' => 'federal',
                'location' => 'Ibadan',
                'state' => 'Oyo',
                'website' => 'https://ui.edu.ng',
                'sort_order' => 2,
            ],
            [
                'name' => 'Obafemi Awolowo University',
                'short_name' => 'OAU',
                'slug' => 'oau',
                'type' => 'federal',
                'location' => 'Ile-Ife',
                'state' => 'Osun',
                'website' => 'https://oauife.edu.ng',
                'sort_order' => 3,
            ],
            [
                'name' => 'University of Nigeria',
                'short_name' => 'UNN',
                'slug' => 'unn',
                'type' => 'federal',
                'location' => 'Nsukka',
                'state' => 'Enugu',
                'website' => 'https://unn.edu.ng',
                'sort_order' => 4,
            ],
            [
                'name' => 'Ahmadu Bello University',
                'short_name' => 'ABU',
                'slug' => 'abu',
                'type' => 'federal',
                'location' => 'Zaria',
                'state' => 'Kaduna',
                'website' => 'https://abu.edu.ng',
                'sort_order' => 5,
            ],
            [
                'name' => 'University of Benin',
                'short_name' => 'UNIBEN',
                'slug' => 'uniben',
                'type' => 'federal',
                'location' => 'Benin City',
                'state' => 'Edo',
                'website' => 'https://uniben.edu',
                'sort_order' => 6,
            ],
            [
                'name' => 'University of Ilorin',
                'short_name' => 'UNILORIN',
                'slug' => 'unilorin',
                'type' => 'federal',
                'location' => 'Ilorin',
                'state' => 'Kwara',
                'website' => 'https://unilorin.edu.ng',
                'sort_order' => 7,
            ],
            [
                'name' => 'University of Jos',
                'short_name' => 'UNIJOS',
                'slug' => 'unijos',
                'type' => 'federal',
                'location' => 'Jos',
                'state' => 'Plateau',
                'website' => 'https://unijos.edu.ng',
                'sort_order' => 8,
            ],
            [
                'name' => 'University of Calabar',
                'short_name' => 'UNICAL',
                'slug' => 'unical',
                'type' => 'federal',
                'location' => 'Calabar',
                'state' => 'Cross River',
                'website' => 'https://unical.edu.ng',
                'sort_order' => 9,
            ],
            [
                'name' => 'University of Port Harcourt',
                'short_name' => 'UNIPORT',
                'slug' => 'uniport',
                'type' => 'federal',
                'location' => 'Port Harcourt',
                'state' => 'Rivers',
                'website' => 'https://uniport.edu.ng',
                'sort_order' => 10,
            ],
            [
                'name' => 'University of Maiduguri',
                'short_name' => 'UNIMAID',
                'slug' => 'unimaid',
                'type' => 'federal',
                'location' => 'Maiduguri',
                'state' => 'Borno',
                'website' => 'https://unimaid.edu.ng',
                'sort_order' => 11,
            ],
            [
                'name' => 'Bayero University',
                'short_name' => 'BUK',
                'slug' => 'buk',
                'type' => 'federal',
                'location' => 'Kano',
                'state' => 'Kano',
                'website' => 'https://buk.edu.ng',
                'sort_order' => 12,
            ],
            [
                'name' => 'University of Abuja',
                'short_name' => 'UNIABUJA',
                'slug' => 'uniabuja',
                'type' => 'federal',
                'location' => 'Gwagwalada, Abuja',
                'state' => 'FCT',
                'website' => 'https://uniabuja.edu.ng',
                'sort_order' => 13,
            ],
            [
                'name' => 'Federal University of Technology, Akure',
                'short_name' => 'FUTA',
                'slug' => 'futa',
                'type' => 'federal',
                'location' => 'Akure',
                'state' => 'Ondo',
                'website' => 'https://futa.edu.ng',
                'sort_order' => 14,
            ],
            [
                'name' => 'Federal University of Technology, Owerri',
                'short_name' => 'FUTO',
                'slug' => 'futo',
                'type' => 'federal',
                'location' => 'Owerri',
                'state' => 'Imo',
                'website' => 'https://futo.edu.ng',
                'sort_order' => 15,
            ],
            [
                'name' => 'Federal University of Technology, Minna',
                'short_name' => 'FUTMINNA',
                'slug' => 'futminna',
                'type' => 'federal',
                'location' => 'Minna',
                'state' => 'Niger',
                'website' => 'https://futminna.edu.ng',
                'sort_order' => 16,
            ],
            [
                'name' => 'Nnamdi Azikiwe University',
                'short_name' => 'UNIZIK',
                'slug' => 'unizik',
                'type' => 'federal',
                'location' => 'Awka',
                'state' => 'Anambra',
                'website' => 'https://unizik.edu.ng',
                'sort_order' => 17,
            ],

            // State Universities
            [
                'name' => 'Lagos State University',
                'short_name' => 'LASU',
                'slug' => 'lasu',
                'type' => 'state',
                'location' => 'Ojo, Lagos',
                'state' => 'Lagos',
                'website' => 'https://lasu.edu.ng',
                'sort_order' => 50,
            ],
            [
                'name' => 'Ekiti State University',
                'short_name' => 'EKSU',
                'slug' => 'eksu',
                'type' => 'state',
                'location' => 'Ado-Ekiti',
                'state' => 'Ekiti',
                'website' => 'https://eksu.edu.ng',
                'sort_order' => 51,
            ],
            [
                'name' => 'Rivers State University',
                'short_name' => 'RSU',
                'slug' => 'rsu',
                'type' => 'state',
                'location' => 'Port Harcourt',
                'state' => 'Rivers',
                'website' => 'https://rsu.edu.ng',
                'sort_order' => 52,
            ],
            [
                'name' => 'Delta State University',
                'short_name' => 'DELSU',
                'slug' => 'delsu',
                'type' => 'state',
                'location' => 'Abraka',
                'state' => 'Delta',
                'website' => 'https://delsu.edu.ng',
                'sort_order' => 53,
            ],
            [
                'name' => 'Ambrose Alli University',
                'short_name' => 'AAU',
                'slug' => 'aau-ekpoma',
                'type' => 'state',
                'location' => 'Ekpoma',
                'state' => 'Edo',
                'website' => 'https://aauekpoma.edu.ng',
                'sort_order' => 54,
            ],
            [
                'name' => 'Ebonyi State University',
                'short_name' => 'EBSU',
                'slug' => 'ebsu',
                'type' => 'state',
                'location' => 'Abakaliki',
                'state' => 'Ebonyi',
                'website' => 'https://ebsu-edu.net',
                'sort_order' => 55,
            ],

            // Private Universities
            [
                'name' => 'Covenant University',
                'short_name' => 'CU',
                'slug' => 'covenant',
                'type' => 'private',
                'location' => 'Ota',
                'state' => 'Ogun',
                'website' => 'https://covenantuniversity.edu.ng',
                'sort_order' => 100,
            ],
            [
                'name' => 'Babcock University',
                'short_name' => 'BU',
                'slug' => 'babcock',
                'type' => 'private',
                'location' => 'Ilishan-Remo',
                'state' => 'Ogun',
                'website' => 'https://babcock.edu.ng',
                'sort_order' => 101,
            ],
            [
                'name' => 'Landmark University',
                'short_name' => 'LMU',
                'slug' => 'landmark',
                'type' => 'private',
                'location' => 'Omu-Aran',
                'state' => 'Kwara',
                'website' => 'https://lmu.edu.ng',
                'sort_order' => 102,
            ],
            [
                'name' => 'Bells University of Technology',
                'short_name' => 'BELLSTECH',
                'slug' => 'bells',
                'type' => 'private',
                'location' => 'Ota',
                'state' => 'Ogun',
                'website' => 'https://bellsuniversity.edu.ng',
                'sort_order' => 103,
            ],
            [
                'name' => 'Pan-Atlantic University',
                'short_name' => 'PAU',
                'slug' => 'pau',
                'type' => 'private',
                'location' => 'Lagos',
                'state' => 'Lagos',
                'website' => 'https://pau.edu.ng',
                'sort_order' => 104,
            ],
            [
                'name' => 'Afe Babalola University',
                'short_name' => 'ABUAD',
                'slug' => 'abuad',
                'type' => 'private',
                'location' => 'Ado-Ekiti',
                'state' => 'Ekiti',
                'website' => 'https://abuad.edu.ng',
                'sort_order' => 105,
            ],
        ];

        foreach ($universities as $university) {
            University::updateOrCreate(
                ['slug' => $university['slug']],
                array_merge($university, [
                    'country' => 'Nigeria',
                    'is_active' => true,
                ])
            );
        }
    }
}
