<template>
    <aside v-show="!props.isCollapsed" :class="props.containerClass">
        <div class="h-14 flex items-center justify-between px-4 border-b border-border/40 shrink-0">
            <span class="text-sm font-semibold tracking-tight text-foreground">Writing Assistant</span>
            <Tooltip>
                <TooltipTrigger asChild>
                    <Button variant="ghost" size="icon" class="h-7 w-7">
                        <BookCheck class="h-3.5 w-3.5" />
                    </Button>
                </TooltipTrigger>
                <TooltipContent>Manage Citations</TooltipContent>
            </Tooltip>
        </div>
        <div class="flex-1 overflow-y-auto custom-scrollbar">
            <div class="p-4 space-y-6">
                <AISidebar :project="props.project" :chapter="props.chapter"
                    :is-generating="props.isGenerating" :selected-text="props.selectedText"
                    :is-loading-suggestions="props.isLoadingSuggestions"
                    :show-citation-helper="props.showCitationHelper" :chapter-content="props.chapterContent"
                    :current-word-count="props.currentWordCount" :target-word-count="props.targetWordCount"
                    @start-streaming-generation="props.handleAIGeneration"
                    @get-ai-suggestions="props.getAISuggestions"
                    @update:show-citation-helper="props.updateCitationHelper"
                    @insert-citation="props.insertCitation" @check-citations="props.checkCitations" />

                <DefensePreparationPanel :show-defense-prep="props.showDefensePrep"
                    :questions="props.defenseQuestions" :is-loading="props.isLoadingDefenseQuestions"
                    :is-generating="props.isGeneratingDefenseQuestions" :chapter-context="props.chapterContext"
                    :defense-watcher="props.defenseWatcher" :auto-generate-enabled="props.autoGenerateDefense"
                    @update:show-defense-prep="props.handleDefensePanelToggle"
                    @generate-more="props.generateNewDefenseQuestions"
                    @toggle-auto-generate="props.handleDefenseAutoToggle"
                    @refresh="props.refreshDefenseQuestions"
                    @mark-helpful="props.markQuestionHelpful" @hide-question="props.hideQuestion" />

                <DataCollectionPanel :chapter-id="props.chapter.id"
                    :content="props.chapterContent" />
            </div>
        </div>
    </aside>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import AISidebar from '@/components/chapter-editor/AISidebar.vue';
import DefensePreparationPanel from '@/components/chapter-editor/DefensePreparationPanel.vue';
import DataCollectionPanel from '@/components/chapter-editor/DataCollectionPanel.vue';
import { BookCheck } from 'lucide-vue-next';
import type { Chapter, Project } from '@/types/chapter-editor';
import type { Ref } from 'vue';

interface DefenseWatcherState {
    meetsThreshold: boolean;
    shouldShowProgress: boolean;
    progressPercentage: number;
    wordsRemaining: number;
    hasTriggeredGeneration: Ref<boolean> | boolean;
    threshold: number;
    statusMessage: string;
}

const props = defineProps<{
    project: Project;
    chapter: Chapter;
    isGenerating: boolean;
    selectedText: string;
    isLoadingSuggestions: boolean;
    showCitationHelper: boolean;
    chapterContent: string;
    currentWordCount: number;
    targetWordCount: number;
    handleAIGeneration: (type: 'progressive' | 'outline' | 'improve' | 'section' | 'rephrase' | 'expand', options?: any) => void;
    getAISuggestions: () => void;
    updateCitationHelper: (value: boolean) => void;
    insertCitation: (citation: string) => void;
    checkCitations: () => void;
    showDefensePrep: boolean;
    defenseQuestions: any[];
    isLoadingDefenseQuestions: boolean;
    isGeneratingDefenseQuestions: boolean;
    chapterContext: {
        chapter_number: number;
        chapter_title: string;
        word_count: number;
    };
    defenseWatcher: DefenseWatcherState;
    autoGenerateDefense: boolean;
    handleDefensePanelToggle: (value: boolean) => void;
    generateNewDefenseQuestions: () => void;
    handleDefenseAutoToggle: (value: boolean) => void;
    refreshDefenseQuestions: () => void;
    markQuestionHelpful: (questionId: number, helpful: boolean) => void;
    hideQuestion: (questionId: number) => void;
    isCollapsed?: boolean;
    containerClass?: string;
}>();
</script>
